env:
    - BAZEL_VERSION='0.5.4'

dist: trusty

sudo: true

before_install:
    - ./travis/before_install.sh

script:
    - bazel build //...

deploy:
    provider: script
    script: bazel run deploy_www.lizanddustin.com
